import { Github, Linkedin, Mail, FileText, ArrowUpRight, BrainCircuit, Database, Server, Cloud, Sparkles, ExternalLink } from 'lucide-react';
import { motion } from 'framer-motion';
import dynamic from 'next/dynamic';

const SemanticGraph = dynamic(() => import('../components/SemanticGraph'), { ssr: false, loading: () => <div className="graph-fallback" aria-hidden="true" /> });

const config = { name:'Kazi Afroz Alam', role:'Backend AI Engineer', location:'Bangalore, India', email:'afrozalam.8760@gmail.com', phone:'+91 8597037748', linkedin:'https://linkedin.com/in/kazi-afroz-alam', github:'https://github.com/KaziAfrozAlam', cv:'/resume/Kazi-Afroz-Alam-Resume.pdf', currentCompany:'FlyRank AI', currentRole:'Backend AI Engineering Intern' };

const metrics=[['29','BI dashboards'],['8+','ML models'],['60%','manual reporting reduction'],['2','AI/ML publications']];
const skills=[['AI / ML / Backend',['Python','FastAPI','RESTful APIs','Scikit-learn','TensorFlow','Embeddings','Retrieval Fundamentals']],['Cloud / DevOps',['AWS EC2','AWS S3','AWS SageMaker','Docker','Git','GitHub','Linux','CI/CD']],['Data Engineering',['SQL','MySQL','SQLite','MongoDB','ETL Pipelines','Data Modelling','Pandas','NumPy']],['Analytics / BI',['Power BI','DAX','Tableau','Excel','Statistical Analysis','Trend Analysis']],['Data Acquisition',['BeautifulSoup','Scrapy','OpenCV']]];
const experience=[
 {company:'FlyRank AI',role:'Backend AI Engineering Intern',date:'Jul 2026 – Present',tag:'CURRENT',items:['Semantic content graph for 20–200 post libraries','Embedding-based retrieval and semantic relatedness','Dynamic recomputation of affected posts','Review workflow with persistent rejection rules','Validated REST API and background pipelines']},
 {company:'Rooman Technologies',role:'AI/ML Engineer Intern',date:'Feb 2025 – May 2025',items:['Engineered 8+ classification/regression models','Automated model scoring pipelines','Reduced manual reporting steps by approximately 40%','Improved F1 scores by approximately 15%','Worked with imbalanced churn/customer-risk datasets']},
 {company:'VaultOfCodes',role:'Python Programming Intern',date:'Nov 2023 – Dec 2023',items:['Python scraping with BeautifulSoup and Scrapy','Data cleaning and scheduled collection','Reduced dataset noise by approximately 30%','Saved approximately 5 hours/week']}
];
const projects=[
 {n:'01',title:'Task Management REST API',stack:['FastAPI','PostgreSQL','Docker','Supabase','JWT','Python'],desc:'Production-oriented backend with CRUD, validation, health checks, OpenAPI docs, persistence, authentication, authorization and protected routes.',flow:'CLIENT → FASTAPI → AUTH → SERVICE → DATABASE'},
 {n:'02',title:'Customer Churn Prediction API',stack:['Python','FastAPI','Scikit-learn','Docker','AWS EC2','ECR','S3','SageMaker'],desc:'End-to-end ML deployment using 7,000+ telecom records, model training and a containerized prediction API.',flow:'DATA → TRAINING → SAGEMAKER → MODEL → FASTAPI → DOCKER → AWS'},
 {n:'03',title:'Real-Time Twitter Sentiment Analysis',stack:['Python','NLP','PySpark ML','Apache Kafka','Spark Streaming'],desc:'Streaming NLP pipeline processing live-style events through Kafka and Spark Streaming.',flow:'STREAM → KAFKA → SPARK STREAMING → PYSPARK ML → SENTIMENT'},
 {n:'04',title:'Business Intelligence Dashboards — Power BI',stack:['Power BI','SQL','Power Query','DAX'],desc:'14 dashboards spanning Sales, HR and Finance with interactive KPIs, drill-through and slicers.',flow:'DATA → SQL → POWER QUERY → DAX → KPI'},
 {n:'05',title:'Business Intelligence Dashboards — Tableau',stack:['Tableau','LOD expressions','Calculated fields','Parameters'],desc:'15 workbooks across 6+ datasets covering Sales, Logistics and Environmental data with multi-source joins.',flow:'SOURCES → JOINS → CALCULATIONS → LOD → DASHBOARD'}
];

function Reveal({children,delay=0}:{children:React.ReactNode,delay?:number}){return <motion.div initial={{opacity:0,y:28}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.15}} transition={{duration:.65,delay}}>{children}</motion.div>}
function Section({id,label,title,children}:{id:string,label:string,title:string,children:React.ReactNode}){return <section id={id} className="section"><div className="section-head"><span className="eyebrow">{label}</span><h2>{title}</h2></div>{children}</section>}

export default function Home(){return <main>
<header className="nav"><a className="brand" href="#top">KAA<span>/</span>AI</a><nav>{['About','Projects','Skills','Experience','Research','Contact'].map(x=><a key={x} href={'#'+x.toLowerCase()}>{x}</a>)}</nav><a className="nav-cta" href={`mailto:${config.email}`}>Let's Talk <ArrowUpRight size={15}/></a></header>
<section id="top" className="hero"><div className="hero-grid"><div className="hero-copy"><div className="status"><span/> Currently building at FlyRank AI</div><div className="eyebrow">BACKEND AI ENGINEER • ML SYSTEMS • BUILDING WITH INTELLIGENCE</div><h1>Building intelligent systems <em>from data, retrieval, and code.</em></h1><p className="hero-sub">Backend AI Engineer focused on RAG, embeddings, retrieval systems, machine learning, backend APIs, and cloud deployment.</p><div className="actions"><a className="btn primary" href="#projects">Explore My Work <ArrowUpRight size={17}/></a><a className="btn ghost" href={`mailto:${config.email}`}>Let's Connect <Mail size={17}/></a></div><div className="socials"><a href={config.github} target="_blank"><Github size={18}/> GitHub</a><a href={config.linkedin} target="_blank"><Linkedin size={18}/> LinkedIn</a><a href={config.cv}><FileText size={18}/> CV</a></div></div><div className="hero-visual"><SemanticGraph/></div></div><div className="metrics">{metrics.map(([n,l])=><div key={l}><strong>{n}</strong><span>{l}</span></div>)}</div></section>

<Section id="about" label="01 / SYSTEM MINDSET" title="Engineering intelligence, one system at a time."><div className="about-grid"><div><p className="lead">Kazi combines backend engineering, AI/ML, data engineering, analytics and cloud deployment to turn complex data into useful systems.</p><p>His current work centers on semantic retrieval, embeddings, content graphs, dynamic pipelines and validated APIs. The through-line is practical: understand the data, model the problem, build the system, validate it, deploy it, then iterate.</p></div><div className="stack-diagram">{['DATA','PYTHON','ML / EMBEDDINGS','FASTAPI','DOCKER','AWS','PRODUCTION'].map((x,i)=><motion.div key={x} className="stack-row" initial={{x:-15,opacity:0}} whileInView={{x:0,opacity:1}} transition={{delay:i*.07}}>{x}{i<6&&<span>↓</span>}</motion.div>)}</div></div></Section>

<section className="build-section"><div className="build-label">CURRENTLY BUILDING</div><div className="build-title"><span>FlyRank AI</span><strong>Semantic Content Graph</strong></div><p>A 20–200 post content library modeled as a relatedness graph, using embeddings and retrieval rather than simple keyword overlap.</p><div className="flow">{['CONTENT','CHUNK / REPRESENT','EMBEDDINGS','SEMANTIC GRAPH','RELATEDNESS','LINK SUGGESTIONS','REVIEW','PUBLISH'].map((x,i)=><div className="flow-node" key={x}><span>{String(i+1).padStart(2,'0')}</span>{x}</div>)}</div><div className="feature-points">{experience[0].items.map(x=><div key={x}><Sparkles size={16}/>{x}</div>)}</div></section>

<Section id="projects" label="02 / SELECTED SYSTEMS" title="Projects, presented as systems—not screenshots."><div className="project-list">{projects.map((p,i)=><Reveal key={p.n} delay={i*.04}><article className={'project '+(i===1?'featured':'')}><div className="project-meta"><span>{p.n}</span><span>CASE STUDY</span></div><div className="project-main"><div><h3>{p.title}</h3><p>{p.desc}</p><div className="chips">{p.stack.map(s=><span key={s}>{s}</span>)}</div></div><div className="architecture"><div className="arch-label">SYSTEM FLOW</div><code>{p.flow}</code><div className="arch-grid">{p.flow.split(' → ').map(x=><span key={x}>{x}</span>)}</div></div></div></article></Reveal>)}</div></Section>

<Section id="skills" label="03 / ENGINEERING STACK" title="Tools are only useful when they connect."><div className="skills-grid">{skills.map(([cat,items],i)=><Reveal key={cat} delay={i*.05}><div className="skill-card"><div className="skill-icon">{i===0?<BrainCircuit size={21}/>:i===1?<Cloud size={21}/>:i===2?<Database size={21}/>:i===3?<Sparkles size={21}/>:<Server size={21}/>}</div><h3>{cat}</h3><div className="chips">{(items as string[]).map(x=><span key={x}>{x}</span>)}</div></div></Reveal>)}</div></Section>

<Section id="experience" label="04 / EXPERIENCE" title="Building toward production.<"><div className="timeline">{experience.map((e,i)=><Reveal key={e.company}><article className="timeline-item"><div className="timeline-dot">0{i+1}</div><div className="timeline-content"><div className="timeline-top"><span>{e.date}</span>{e.tag&&<b>{e.tag}</b>}</div><h3>{e.company}</h3><h4>{e.role}</h4><ul>{e.items.map(x=><li key={x}>{x}</li>)}</ul></div></article></Reveal>)}</div></Section>

<Section id="research" label="05 / RESEARCH + CREDENTIALS" title="Curiosity that reaches beyond the product."><div className="research-grid"><article><span className="card-kicker">PUBLICATION 01</span><h3>Automated Evaluation and Assessment System Using AI, ML, and NLP</h3><p>Springer Singapore · ICDSMLA 2024 · Published 2026</p></article><article><span className="card-kicker">PUBLICATION 02</span><h3>Unveiling the Trends in Machine Learning</h3><p>IJSRCSEIT · Volume 10, Issue 7 · May–June 2024</p></article></div><div className="credential-strip"><span>Machine Learning Specialization — DeepLearning.AI & Stanford Online</span><span>Foundation: Introduction to LangChain - Python — LangChain</span><span>Databricks Fundamentals — Databricks Academy</span><span>Cloud Computing — NPTEL</span><span>SQL (Basic) — HackerRank</span><span>Python (Basic) — HackerRank</span></div></Section>

<section className="method"><div className="method-copy"><span className="eyebrow">HOW I BUILD</span><h2>From uncertainty to a deployed system.</h2></div><div className="method-flow">{['UNDERSTAND','MODEL','BUILD','VALIDATE','DEPLOY','ITERATE'].map((x,i)=><div key={x}><span>0{i+1}</span><strong>{x}</strong></div>)}</div></section>
<section className="future"><span className="eyebrow">THE NEXT SYSTEM</span><h2>CAPSTONE — <em>COMING SOON</em></h2><p>A future AI engineering project exploring a real-world problem through intelligent systems, retrieval, machine learning, and production-ready backend infrastructure.</p><div className="future-line"/></section>

<section id="contact" className="contact"><div><span className="eyebrow">06 / CONTACT</span><h2>Let's build something <em>intelligent.</em></h2><p>Interested in AI engineering, backend systems, machine learning, or building useful technology? Let's connect.</p><div className="actions"><a className="btn primary" href={`mailto:${config.email}`}>Email me <Mail size={17}/></a><a className="btn ghost" href={config.linkedin} target="_blank">Connect on LinkedIn <Linkedin size={17}/></a></div></div><form name="contact" method="POST" data-netlify="true" className="contact-form"><input type="hidden" name="form-name" value="contact"/><label>Name<input required name="name" placeholder="Your name"/></label><label>Email<input required type="email" name="email" placeholder="you@example.com"/></label><label>Message<textarea required name="message" rows={5} placeholder="Tell me what you're building…"/></label><button className="btn primary" type="submit">Send message <ArrowUpRight size={17}/></button></form></section>
<footer><div><strong>KAZI AFROZ ALAM</strong><span>Backend AI Engineer • ML Systems • Building with Intelligence</span></div><div className="footer-links"><a href={config.github}><Github size={17}/></a><a href={config.linkedin}><Linkedin size={17}/></a><a href={`mailto:${config.email}`}><Mail size={17}/></a><a href={config.cv}><FileText size={17}/></a></div><small>© 2026 Kazi Afroz Alam</small></footer>
</main>}
